controller_type: JOINT_IMPEDANCE

is_delta: false

traj_interpolator_cfg:
  traj_interpolator_type: LINEAR_JOINT_POSITION
  time_fraction: 0.95
 
  #joint_kp: [900., 900., 900., 850., 550., 1200., 350.]
  #joint_kd: [260., 260., 260., 240., 140., 260., 90.]
joint_kp: [400., 400., 400., 400., 250., 150.,  50.]
joint_kd: [100., 100., 100., 100.,  45.,  40.,  25.]


state_estimator_cfg:
  is_estimation: true
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0
